project:
  type: website
  output-dir: docs

website:
  title: "JovanWebsite"
  favicon: favicon.png
  navbar:
    logo: logo.png
    left:
      - href: index.qmd
        text: Navigation
      - index.qmd
      - about.qmd
      - travel_experience.qmd
      - relection.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 3
    toc-location: left



